### ISSUE TITLE
Unstakje page is not fitting the screen view with Fees details going unnoticed (very likely)

### ISSUE THREAD

**Issue by DayalKS2** [stafiprotocol/security#10]
Reduce Page size for Unstake. Stake page is fitting to my screen an I see all details clearly. But when I enter Unstake Page, the Unstake fees are hiding down my screen fit size. Its highly likely that users will miss seeing it as the screen looks as if it has all the details and functions. This should be redesigned to fit the screen (I was using Laptop and had it in 100% default zoom)
https://github.com/stafiprotocol/security/assets/94037805/ffc03a73-f360-4c53-a60c-2f36c8ebdf05

**Comment by eesignal** [comment]
not function issue
