### ISSUE TITLE
Zero limit in input field of Unstake

### ISSUE THREAD

**Issue by DayalKS2** [stafiprotocol/security#13]
Can we limit the number of zeros user can add in the input field for UNSTAKE? With too many zeroes allowed, the page UI is broken

![image](https://github.com/stafiprotocol/security/assets/94037805/e6cd13eb-f665-45fc-b1bd-74ceed36c369)

**Comment by DayalKS2** [comment]
![image](https://github.com/stafiprotocol/security/assets/94037805/0d28d9ba-77bb-437a-acd3-8955f4b25a17)

**Comment by eesignal** [comment]
fixed
