### ISSUE TITLE
Unable Stake (Microsoft Browser)

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#15]
![image](https://github.com/stafiprotocol/security/assets/135915618/12686171-db64-4cc6-9619-d53cfe96d713)
![image](https://github.com/stafiprotocol/security/assets/135915618/644b34f6-9eef-41b3-9a56-d202db7379c2)

Unable Stake using Microsoft Browser

Steps to Reproduce
1)Use Microsoft Browser
2)Go to https://test-rtoken-app.stafi.io/rtoken/stake/BNB?tokenStandard=BEP20
3)Connect Wallet using Metamask
4)Stake BNB
5)Confirm Transaction

Error Message Show **Transaction Failed
Please confirm the 0.01 BNB staking transaction in your MetaMask wallet error Retry Details
1 Staking Broadcasting... Packing...**

I make a lot of transaction but still unable to stake bnb.

**Comment by eesignal** [comment]
fixed
