### ISSUE TITLE
Withdrawal transactions are getting failed

### ISSUE THREAD

**Issue by DayalKS2** [stafiprotocol/security#25]
Withdrawal transactions are getting failed. Below is the error from Console.

inpage.js:1 MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction underpriced"}}}' {code: -32603, message: `[ethjs-query] while formatting outputs from RPC '{…e":-32000,"message":"transaction underpriced"}}}'`}code: -32603message: "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}}'"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17

https://github.com/stafiprotocol/security/assets/94037805/9b5a7909-eafa-43dd-baf6-6e2dadcfcd56

**Comment by eesignal** [comment]
fixed
