### ISSUE TITLE
My Wallet balance is read even after disconnecting the wallet

### ISSUE THREAD

**Issue by DayalKS2** [stafiprotocol/security#3]
Even after disconnecting from wallet, Staking page is able to read my account balance.
Steps to reproduce:
1.Connect Wallet
2.Now Disconnect Wallet
3.Now you can see that the STAKE and TRADE buttons which were previously disabled (before connecting wallet initially) are enabled now.
4.Now click Stake button and then click MAX. This will fill the field with your balance even though it appears everywhere that you have not established connection with the wallet.

This is a security issue.

https://github.com/stafiprotocol/security/assets/94037805/b79b3065-cf4d-4369-bcd0-8bf77df15dc0

**Comment by signalxu** [comment]
fixed
