### ISSUE TITLE
Unable to clear recent transaction

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#30]
![image](https://github.com/stafiprotocol/security/assets/135915618/645c78bc-19b1-4749-a366-db2d28e286f6)

I want to clear my transaction history but unable to clear recent transaction history.

**Comment by Sara8721** [comment]
Hey, thanks for your reports! Plz share your Telegram ID here, our team member will DM to synchronize bounty with you.

**Comment by cryptofanatic777** [comment]
Hello my telegram https://t.me/CRYPTOFANATIC111
