### ISSUE TITLE
Modifier onlyStakeManager 

### ISSUE THREAD

**Issue by DimaKovalenko17** [stafiprotocol/security#31]
Good afternoon, found a vulnerability, this modifier OnlyStakeManager is used to restrict access to certain functions only to the stakeManagerAddress. 
this modifier does not provide any additional access control checks beyond verifying the sender's address.
If an attacker gains control of the address. He may be able to make unrestricted use of the function

contract StakePool is IStakePool {
    using SafeERC20 for IERC20;
    using SafeMath for uint256;

    bytes32 private constant stakeManagerAddressSlot =
        bytes32(uint256(keccak256("StakePool.proxy.stakeManagerAddressSlot")) - 1);

    bytes32 private constant govStakeManagerAddressSlot =
        bytes32(uint256(keccak256("StakePool.proxy.govStakeManagerAddressSlot")) - 1);
///* THIS IS VULNERIBLIES ///*
    modifier onlyStakeManager() {
        require(msg.sender == stakeManagerAddress(), "only stakeManager");
        _;
    }

**Comment by Tore19** [comment]
@DimaKovalenko17  Usually the contract logic of access verification is implemented in this way, and we believe that there is no problem about this.
