### ISSUE TITLE
StakePool.sol There is no input validation in the code 

### ISSUE THREAD

**Issue by DimaKovalenko17** [stafiprotocol/security#32]
There is no input validation in the code, there is no sufficient input validation on the function arguments.
 Lack of Input Validation: The contract does not perform sufficient input validation on the function arguments. 
 
function undelegate(uint256 _validator, uint256 _claimAmount) external override onlyStakeManager { 
        address valAddress = IGovStakeManager(govStakeManagerAddress()).getValidatorContract(_validator); 
        IValidatorShare(valAddress).sellVoucher_new(_claimAmount, _claimAmount);  
        
![Без имени](https://github.com/stafiprotocol/security/assets/140205467/018ee796-f262-4c6f-bf08-e7c65d3faa8b)

**Comment by Tore19** [comment]
@DimaKovalenko17 In fact, both the StakeManager contract and the ValidatorShare contract will validate the parameters, so there is no need to validate here.
