### ISSUE TITLE
Matic Balance

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#35]
![image](https://github.com/stafiprotocol/security/assets/135915618/a73e8150-df1d-4f21-9d23-36ad222acd32)

There is no current matic balance displayed on my dashboard.

My expectation there must be an input value in the matic so that the user can immediately know how much their matic balance is

StaFi native address
35mojVGvEJWjPbs3F3p9k5Zu3DH6ys7Fz1Hc4okgwwFtSHTA

**Comment by Tore19** [comment]
It will show your balance when you switch to the right network.
