### ISSUE TITLE
Matic Hover

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#36]
![image](https://github.com/stafiprotocol/security/assets/135915618/2a039386-8306-4170-b835-62a5e05afb63)

The one near the return has no details on the hover.

My expectation is that when I put the mouse arrow on the hover, details will be displayed 

StaFi native address
35mojVGvEJWjPbs3F3p9k5Zu3DH6ys7Fz1Hc4okgwwFtSHTA

**Comment by Tore19** [comment]
It is designed to click to jump to the doc.
