### ISSUE TITLE
rMATIC Quickswap Testnet

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#37]
![image](https://github.com/stafiprotocol/security/assets/135915618/2269ba3c-c330-4bc6-8c75-55daaaf98541)

I used the quickswap link but I didn't see any rMATIC testnet

My expectation is that when I click on the link on quickswap or DEX, it should go directly to the testnet so that the testnet user can buy rMATIC to test the rMATIC stafi testnet

**Comment by Tore19** [comment]
There is only mainnet link for Quickswap DEX.
