### ISSUE TITLE
Matic Unstake

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#38]
![image](https://github.com/stafiprotocol/security/assets/135915618/04431eb1-ff2b-4253-9fa1-a1e762169b5b)

![image](https://github.com/stafiprotocol/security/assets/135915618/fb1ee4ee-c2ee-4539-af0e-8fa2e1249030)

On the unstake dashboard, the button is not colored green, but unstake can be clicked even if there is no matic stake
My expectation is that the unstake button should be disabled when there is no matic placed on the stake.

**Comment by Tore19** [comment]
It would be better designed like this, so that any user can open the unstake popup for more information.
