### ISSUE TITLE
Matic Reward

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#39]
![image](https://github.com/stafiprotocol/security/assets/135915618/060f4b11-8dd3-4fc3-920b-ef6bc52086e9)

In MATIC Reward, there is no information or details in 1W 1M 3M 6M and ALL

My expectation is that when I stake, there will be details or information displayed on the MATIC Reward dashboard

**Comment by Tore19** [comment]
After the stake, you need to wait until the next era before there will be reward. It may need to wait for around 1 day on the test network. Please check again.
