### ISSUE TITLE
Add Token to Your Wallet

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#40]
![image](https://github.com/stafiprotocol/security/assets/135915618/9e18e684-e307-4c37-9671-c2e97030b2fb)

https://github.com/stafiprotocol/security/assets/135915618/3292fe38-4f49-4bc4-b1cc-6f351814cf2a

When I use the "Add Token to Your Wallet" change network appears

My expectation is when I use "Add Token to Your Wallet" I will go to my metamask wallet and add a token to MATIC

**Comment by Tore19** [comment]
Fixed.
