### ISSUE TITLE
Est Reward

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#41]
![image](https://github.com/stafiprotocol/security/assets/135915618/bdb96d25-1af5-42c9-b5ff-577966e67dcf)
The issue in Est. Reward no data or information appears on how many rewards are or will be my rewards.

My suggestions should put transparency data for users on how many rewards they will be and I suggest also to put calculator so they can compute their rewards.

**Comment by Tore19** [comment]
You need to wait until the next era before there will be reward.
