### ISSUE TITLE
Transaction Cost

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#43]
![image](https://github.com/stafiprotocol/security/assets/135915618/cee2366f-0e72-4d74-b89e-edebb7fcf3c0)

The fees spent are even higher than receiving assets

A minimum requirement should be set for users to unstake matic so they don't lose out on gas fees

This should be applied especially to the mainnet.

**Comment by Tore19** [comment]
We believe it depends on the users themselves, usually users will not stake a very small amount of MATIC.
