### ISSUE TITLE
Block Explorer

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#44]
![image](https://github.com/stafiprotocol/security/assets/135915618/b00e991c-ee22-4924-b92d-a3683f85d154)

When I clicked on the block explorer, it was not directly linked to my wallet address

My expectation is that when I click on the block explorer, it will go to the explorer of my wallet address..

**Comment by Tore19** [comment]
This is just to go to the block explorer, it has nothing to do with the user address for the time being.

**Comment by cryptofanatic777** [comment]
On other platforms I use that and go directly to my wallet address.
