### ISSUE TITLE
Withdraw Unstaked MATIC Hover

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#45]
![image](https://github.com/stafiprotocol/security/assets/135915618/2b8e8717-653a-44be-9f8e-c79efba087b8)

On Withdraw Unstaked MATIC hover, no details or information appears regarding the Withdraw Unstaked MATIC

My expectation is that when I put the mouse arrow on the Withdraw Unstaked MATIC hover, details will be displayed

**Comment by Tore19** [comment]
Fixed.
