### ISSUE TITLE
Error Block Explorer

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#47]
![image](https://github.com/stafiprotocol/security/assets/135915618/4a68f099-c116-4080-9821-0c53388573b2)

When I click on the error transaction, no block explorer appears, unlike in the confirm transaction, there is a block explorer that appears.

My expectation is that even if the transaction fails or errors, there is still a block explorer that appears to be transparent to users and they can see that it has failed transaction.

**Comment by Tore19** [comment]
Fixed.
