### ISSUE TITLE
Time Left

### ISSUE THREAD

**Issue by cryptofanatic777** [stafiprotocol/security#48]
![image](https://github.com/stafiprotocol/security/assets/135915618/c74727e9-6ee0-4bfc-b9c3-5bcc77669859)

In Time Left the issue here is that the countdown doesn't seem to move

I suggest In Time Left, the hours minutes and seconds should also be displayed, this is a great help to users to properly monitor their unstake assets.

**Comment by Tore19** [comment]
We will consider this suggestion in the future.
