### ISSUE TITLE
APY or APR?

### ISSUE THREAD

**Issue by DayalKS2** [stafiprotocol/security#8]
FAQ section talks about APY for rewards, where as the STAKE page shows Reward in APR. Since APR is different than APY, I would suggest to use the one or other, otherwise user will be mislead

![image](https://github.com/stafiprotocol/security/assets/94037805/648bfcfa-08ad-4aed-91db-dce36c4ff0fa)

**Comment by DayalKS2** [comment]
![image](https://github.com/stafiprotocol/security/assets/94037805/908fc59f-00f8-45e5-8c8a-dfbee77b8547)
![image](https://github.com/stafiprotocol/security/assets/94037805/253b5ee6-1c17-4697-a67e-f80a38497d99)

**Comment by eesignal** [comment]
APR
